apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ical-merger.fullname" . }}
  labels:
    {{- include "ical-merger.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ical-merger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ical-merger.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if or .Values.podAnnotations (not .Values.config.existingConfigSecret) }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if not .Values.config.existingConfigSecret }}
        checksum/config: {{ include "ical-merger.config" . | sha256sum | quote }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ICAL_MERGER_CONFIG_FILE
              value: /etc/ical-merger/config.toml
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/ical-merger
              readOnly: true
      volumes:
        - name: config
          {{- if .Values.config.existingConfigSecret }}
          secret:
            secretName: {{ .Values.config.existingConfigSecret }}
            items:
              - key: config.toml
                path: config.toml
          {{- else }}
          configMap:
            name: {{ include "ical-merger.fullname" . }}-config
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
